### PR TITLE
[pvr.hts] fill the VFS buffer on a separate thread

### PR DESCRIPTION
**Pull request by Jalle19**
@adamsutton can you review this? I'll start testing it at home tonight, I have to upgrade my HTPC anyway.
@opdenkamp you can also take a look if you have time

### CODE REVIEW

**Comment by opdenkamp** [comment]
just one question: do we really need a setting for this?

**Comment by Jalle19** [comment]
@opdenkamp personally I'd say we don't, it was Adam's idea to add it. I'm afraid some users will see it and think "wtf I don't want any extra buffering", turn it to zero and watch their recordings stutter. If @adamsutton is fine with removing it then I'll remove it.

**Comment by adamsutton** [comment]
@opdenkamp @Jalle19 it's probably overkill, drop it.

**Comment by adamsutton** [comment]
Something feels a bit wrong about the condition handling, I'm not convinced about it being used in both directions (though I'm not really sure why). And I'm not sure we need to stall in the read() call unless there is NO data available.

I'm feeling like shit today though, so I really can't focus on it properly, I'll try and take a look in a couple of days.

**Comment by Jalle19** [comment]
If we return `-1` from the read method (which we could if we don't wait for data), Kodi may decide the stream died and stop playback. At least that's how I figured it.

**Comment by adamsutton** [comment]
@Jalle19 I wasn't suggesting that, I was suggesting that you return as much data as you can while asking for more. However I think that's also probably wrong, Kodi will probably assume that if we return less than it asked for that that indicates the end of the file. So probably fine as is.

Clearly my brain is seriously addled today!

**Comment by opdenkamp** [comment]
not so sure about that, i haven't checked, but i think len is just the maximum read size (size of the buffer) and returning less is probably fine. though it'll probably just lead to more hammering on this method :)

**Comment by Jalle19** [comment]
I say we play it safe and continue with the old behavior (only return if we can return the requested length).

**Comment by Jalle19** [comment]
I dropped the setting.

**Comment by opdenkamp** [comment]
squash and merge away, before we copy stuff over to a new repos ;-)

**Comment by Jalle19** [comment]
I haven't had time to test it extensively yet, I can try to do that tonight.

**Comment by Jalle19** [comment]
Tried to backport this to a Helix compatible addon but only got lots of missed packets and crap like that. Don't know if I did something wrong yet or if this just doesn't work. Will need to try on an Isengard Kodi to be sure.

**Comment by Jalle19** [comment]
Found the bug, it was something I introduced last minute. This works fine now on Windows.

**Pull request merged**
