### PR TITLE
new pvr.pctv PVR addon

### PR DESCRIPTION
**Pull request by hg1**
Hi all,

here is a new pvr addon that supports Broadway devices and DistanTV mobile by PCTV Systems.

ToDo:
-localization
-and some more :-)

Cheers,
Holger

### CODE REVIEW

**Comment by opdenkamp** [comment]
thanks a lot, but we've just replaced our build system by cmake, and the add-ons are now hosted here: https://github.com/kodi-pvr

have a look at https://github.com/kodi-pvr/pvr.demo for an example of how to port things over.

**Comment by hudokkow** [comment]
@hg1 
Your addon with cmake build system is at https://github.com/hudokkow/pvr.pctv and relevant commit adding it to Kodi's build system is https://github.com/hudokkow/kodi/commit/5849b7d8161fba128422d44bce51e7a784cb2db3

Just ping me here or at http://forum.kodi.tv/showthread.php?tid=219257 and I'll transfer ownership so you can work on it.
Or, if you feel it's good enough to go live, it can go directly to https://github.com/kodi-pvr/ and you fork from there.

**Comment by hg1** [comment]
@hudokkow 
Thanks for initial commit of the addon. That´s great.
There´s still some work to do, like localization, but if you like it can go directly to  https://github.com/kodi-pvr/.

**Comment by hudokkow** [comment]
No problem. Localization will be done by Kodi's translation team. Since I don't understand all the languages under _language/_ and couldn't validate translations accuracy, I dropped everything except _English_.

@FernetMenta, mind pushing to kodi-pvr? After it's in, I'll take care of Kodi's side. btw, I compiled and runtime tested this under ubuntu. Couldn't properly test it since I don't own the hardware.

**Comment by stefansaraev** [comment]
@hudokkow mind syncing FindJsonCpp.cmake from argus to pctv? (filmon needs sync too)

EDIT: [see](https://github.com/stefansaraev/OpenELEC.tv/blob/371ad57a194562a5b4534f333886acea4f1b9331/packages/mediacenter/pvr.pctv/patches/pvr.pctv-01_jsoncpp.patch)

**Comment by hudokkow** [comment]
Will do.

**Comment by hudokkow** [comment]
Done.
https://github.com/hudokkow/pvr.pctv/commits/master
https://github.com/kodi-pvr/pvr.filmon/pull/2

I'll PR to Kodi after kodi-pvr is updated.

ping @FernetMenta

**Comment by opdenkamp** [comment]
https://github.com/kodi-pvr/pvr.pctv

**Comment by hg1** [comment]
Thanks to all

**Comment by FernetMenta** [comment]
@hg1 I recommend some rework mainly cosmetics. 
1) check coding style, don't use tabs
2) check your header and copyrights, i.e. PctvData.cpp doesn't even have a header

**Pull request closed without merging**
