### PR TITLE
backports

### PR DESCRIPTION
**Pull request by FernetMenta**

### CODE REVIEW

**Comment by scarecrow420** [comment]
Pvr.wmc needs the version bumped in clientversion.h file also

**Comment by FernetMenta** [comment]
that's a bit hacky, isn't it. looks like this addons needs some clean-up. It also has a mixture of Pulse-Eight and XBMC copy right headers.
As far as I can see the version in clientversion.h is currently not in sync with addon.xml so I won't change it for this backports.

**Comment by scarecrow420** [comment]
Why do you think hacky? We want the client dll to send it's version to the
backend, the version is compiled into the code, not some text in an XML
file that happens to be present. If someone edits the addon.xml file and
changes the version that doesn't make the dll (and thus the actual code
executing) somehow different. If you have another suggestion to include the
version number in the addon dll let me know

And if it was out of sync already that will be due to a previous PR not
updating it (and me missing it)

**Comment by FernetMenta** [comment]
> Why do you think hacky?

because it requires 2 files to be kept in sync. for compiling a version into a build, you in general generate this file during build process.

**Comment by scarecrow420** [comment]
Sure, but I wasn't sure if we were allowed to customise the builds in that
way (eg a pre build event on visual studio project and I'm assuming some
sort of custom command in the make file for other platforms). Are we
allowed to do that? If so I'd be happy to generate it at build time

**Comment by FernetMenta** [comment]
build systems for the addons is changed to cmake. this task should be finished soon. then you should be able to change it.

**Pull request merged**
