### PR TITLE
[pvr.nextpvr] Added support for ATSC subchannel numbers, fixing 'no tuner available' m...

### PR DESCRIPTION
**Pull request by sub3**
Added support for ATSC subchannel numbers, fixing 'no tuner available' message users were getting with this type of channel
Fixes a problem with playback of radio stations
Added recording artwork
Added fanart

### CODE REVIEW

**Comment by opdenkamp** [comment]
will merge this in asap, but will do #372 first. will probably merge these open PRs locally and push the result so we don't need a load of rebases again

**Comment by sub3** [comment]
Ok thanks. Let me know if you need me to do anything.

**Comment by sub3** [comment]
Hi Lars. Just to be clear - this is going to show up in 14.1 right?

**Comment by Jalle19** [comment]
@sub3 you'll need to create a corresponding PR to the "helix" branch (which got added today).

**Comment by sub3** [comment]
You've got be f*cking kidding me. Are you guys intentionally trying to make life difficult for me? I've been trying to get this small code change, which fixes problems for NextPVR ATSC users, merged for like 2 months now.

**Comment by sub3** [comment]
Sorry about above - just frustrated. I'll create a new helix branch and pull request later today.

**Comment by opdenkamp** [comment]
"master" is always for the upcoming release

**Comment by sub3** [comment]
"helix" was the upcoming release way back when I created the pull request...

**Comment by opdenkamp** [comment]
and unfortunately we were already in beta by that time.

**Comment by sub3** [comment]
and a serious bug effecting all ATSC users can't be fixed in beta?

**Comment by opdenkamp** [comment]
the "serious bug" must be on the backend's side then, expecting 
subchannel numbers in the url that it didn't expect before.
also, using the channel number for tuning is not a good idea. you should 
be using the channel id instead. your add-on will break if users don't 
have "use backend channel numbers" enabled.

**Comment by sub3** [comment]
That's your implementation recommendation, but either way, whether I'd chose to change the addon to use the channel id, or the major.minor number, I would still have needed to submit a change to the addon. I opted for the major.minor number, because this Kodi addon is just reusing streaming interface that is supposed to be human usable from apps like VLC etc, where the user wont know channel ids, but will know channel numbers.

I'll submit the pull request for helix today.

**Comment by opdenkamp** [comment]
I've never recommended to use channel numbers for anything like this. I 
still don't, as it's something that breaks when people change the order 
on one frontend, or use different channel numbers on that frontend, or 
whatever.

There were no minor channel numbers until a couple of months ago when I 
added it, and your add-on didn't change in the meantime. So the reason 
for suddenly requiring those minor channel numbers must have come from 
an update on the backend's side. Which probably also means that the 
backend no longer supports Gotham or older.

**Pull request merged**
