### PR TITLE
[pvr.filmon] removed libcurl + cryptopp dependency

### PR DESCRIPTION
**Pull request by manuelm**
As discussed in https://github.com/xbmc/xbmc/pull/6227 this removes libcurl and cryptopp dependency from pvr.filmon.

### CODE REVIEW

**Comment by opdenkamp** [comment]
looks sane. any objections @denhams or want to test? if not, then it'll be merged today, as we need it for https://github.com/xbmc/xbmc/issues/6227

**Comment by stefansaraev** [comment]
https://github.com/opdenkamp/xbmc-pvr-addons/blob/master/configure.ac#L154-L180

**Comment by manuelm** [comment]
removed + rebased, because somehow I forgot to commit the new md5 files.
should be complete now.

**Comment by ghost** [comment]
Look's okay to me but I'm travelling at the moment and can't test until end
of the month.

**Comment by manuelm** [comment]
Before creating this PR I have done some rudimentary tests. Login (with correct and wrong credentials), fetching channels + epg and playback works. Tested on linux

**Comment by opdenkamp** [comment]
the add-on has been moved here: https://github.com/kodi-pvr/pvr.filmon

**Pull request closed without merging**
