### PR TITLE
[pvr.mythtv] Backport helix 1.11.2

### PR DESCRIPTION
**Pull request by janbar**
Here you will find set of important fixes to be back ported in helix branch

### CODE REVIEW

**Comment by janbar** [comment]
Users cannot compile the addon from my repo will appreciate. Thanks

**Comment by Jalle19** [comment]
I have a feeling @opdenkamp is gonna tell you that only critical fixes can be backported. I don't personally reject to backporting anything as long as you're confident everything will continue to work.

**Comment by janbar** [comment]
Also i requested pull to the bad branch. Sorry. I close it and pull again for "helix"

**Comment by opdenkamp** [comment]
@Jalle19 that was about fixing core components. It's fine for add-ons imo, that's why they're add-ons after all ;-)

**Pull request closed without merging**
