### PR TITLE
[pvr] fix recordings on the timeline

### PR DESCRIPTION
**Pull request by opdenkamp**
for https://github.com/xbmc/xbmc/pull/6566

### CODE REVIEW

**Comment by FernetMenta** [comment]
You know that we already split all addons to their own repos, don't you?

**Comment by opdenkamp** [comment]
yeah i do, check the comment on other pr, this is just in case someone wants to test before it's merged into kodi

**Comment by opdenkamp** [comment]
and so it can be c+p'd into the new pvr.hts one ;-)

**Comment by opdenkamp** [comment]
new PR https://github.com/kodi-pvr/pvr.hts/pull/1

**Pull request closed without merging**
