### PR TITLE
set socket to invalid if open fails, fixes false positive IsOpen respons...

### PR DESCRIPTION
**Pull request by FernetMenta**
fixes continuous "connection lost" messages if backend is not online

### CODE REVIEW

**Comment by wsnipex** [comment]
yay :)

**Comment by FernetMenta** [comment]
@opdenkamp @Jalle19 does this need any version bump?

**Comment by opdenkamp** [comment]
yes it does for any add-on that uses this, or it won't be picked up

**Comment by FernetMenta** [comment]
I don't want to create any conflict with #427 what is the state of the API change. I would meter this then then 427, bump addons for kodi repo, and merge https://github.com/xbmc/xbmc/pull/6367

**Pull request merged**
