### PR TITLE
[pvr.mythtv] Release v1.11.2

### PR DESCRIPTION
**Pull request by janbar**
- Fix stuttering and playback stop when reading ahead

Since Gotham 13.? , player doesn't handle retries when reading zero byte. This is really a strange behavior to read live stream. We found this root cause since few hours ago. Is it possible to backport the fix into Helix branch as soon as possible ?

### CODE REVIEW

**Comment by janbar** [comment]
Also the critical fix (fixed in 1.9.29) was not back ported to Helix. Is it possible to merge with Helix 14.1 ?

**Comment by janbar** [comment]
Many users (from Australia, US and New Zealand) had some channels unreadable. Now closed with this PR.

**Comment by opdenkamp** [comment]
right, it'll have to wait a bit until we've merged in #372 for I*
as for helix, we need to create a tag and branch for helix first, and then need a pr for the new helix branch

@Jalle19 could you create that branch & tag if you've got time atm

**Comment by opdenkamp** [comment]
(branch and tag from the hash that's used in xbmc's helix release btw)

**Comment by Jalle19** [comment]
@opdenkamp sure, will take a look during the weekend if not earlier.

**Comment by janbar** [comment]
Thanks guys, I will waiting for Jalle19 and then will create a PR for the new branch.

**Pull request merged**
