### PR TITLE
Various build fixes

### PR DESCRIPTION
**Pull request by Jalle19**
* fixes building after https://github.com/Jalle19/xbmc-pvr-addons/commit/5587c199f2a6202237dcbe0865dfd4f8558d5cad
* silences some warnings during bootstrap

@MilhouseVH can you build test this?
@janbar can you test that pvr.mythtv still works? I had to change the order of the includes in the Makefile

### CODE REVIEW

**Comment by opdenkamp** [comment]
autotools are stupid! merge away once verified that myth didn't break.

**Comment by Jalle19** [comment]
We should investigate using Jenkins for the addons as well.

**Comment by janbar** [comment]
@Jalle19 testing ...

**Comment by janbar** [comment]
@Jalle19 pvr.mythtv run well. No issues

**Comment by MilhouseVH** [comment]
Bah! Just in the middle of build testing this... :) Though I'm sure it fixes the problem I raised, thanks.

**Comment by Jalle19** [comment]
@MilhouseVH let's hope so (it did for me), sorry I wasted your cycles ;)

**Pull request merged**
