### PR TITLE
[pvr.mythtv] Backport helix 1.12.4

### PR DESCRIPTION
**Pull request by janbar**
Hi,

Here you will find patches to backport in helix branch.

- Support protocol MythTV 0.28-pre:84
- Support protocol MythTV 0.28-pre:85
- Fix C mangling issue: replace jansson by sajson
- Support ARMV6 , ARMV7 Atomic primitives
- Support for RPi2 architecture (ARMv7)
- fix valgrind issue

Best regards

### CODE REVIEW

**Comment by FernetMenta** [comment]
don't you think this change is a bit too big for a dot release? :)

**Comment by janbar** [comment]
Removing the jansson lib i loose 15k lines ;).

**Comment by janbar** [comment]
Some distro (RPMFusion) link the addon dynamically with pre-installed cppmyth and jansson. On Linux, causing C mangling conflict between primitive json_object_get of jansson and pulse-audio.
To resolve it i have linked statically using a version script (addon.map). But using dynamic libs no way. So here i replace jansson parser with sajson which is a single header.

**Comment by janbar** [comment]
Rebased on platform fixes

**Comment by FernetMenta** [comment]
it is up to @opdenkamp if he wants to consider this for backport. IMO this change is much to heavy for a bugfix release.

**Comment by opdenkamp** [comment]
well, it's add-ons and not core, so I'm okay with it since people can revert to a previous build if they like (depending on how things are built and installed on the platform).

whether it's a good idea to do changes this big is another thing, because I agree with @FernetMenta that changes this big should wait for a major release. you risk introducing a whole lot of new issues and this won't go through a beta first.

up to you @janbar, do you think this is _needed_ or not?

**Comment by janbar** [comment]
Hi Lars,

End users would be happy to have included improvements. It is the primary reason i propose it. Many advanced users use it already since few weeks ago and they have reported only good things. Removing mangling conflict, addon will be available on all distros too. So for me it is a GO.

JLB

-----Original Message-----

**Comment by janbar** [comment]
@opdenkamp , i added one commit to handle memory reordering on ARMv6 & ARMv7 arch.

**Comment by janbar** [comment]
I added support for last MythTV service API 5.0. Could rebase ?

**Comment by janbar** [comment]
Rebased. RPi2 users need this PR. @opdenkamp It fixes crash on OpenELEC RPi2 build. Thanks

**Comment by janbar** [comment]
@opdenkamp no more backport since addons are splitted ?

**Comment by opdenkamp** [comment]
helix still uses this repo, so backports can still be done here

**Comment by Lexridge** [comment]
I have now built and installed 1.12.4 on three different Linux computers. RPi2 with OpenELEC, Fedora 21 64bit, and Fedora 21 32bit. The problem is the same on all three platforms. When using the MythTV plugin, it scans the EPG just fine, but will not tune to any channels (Channel Unavailable). if I use the stock Fedora rpm (or the stock OE plugin v1.11.x) it crashes while scanning the EPG, which is why I wanted to just build a newer version myself. 

Perhaps my backend is to old. It is running MythBackend v26.2. What versions of mythbackend are you currently supporting with this build?

**Comment by janbar** [comment]
@Lexridge , you should compile the addon from https://github.com/janbar/pvr.mythtv branch helix, which contains latest version. Instructions to compile it are here: http://kodi.wiki/view/MythTV_PVR/BuildFromSource#Build_MythTV_addon_on_Ubuntu .
Finally the addon runs with 0.26 for testing, It is preferable to use at least 0.27. To fix your issue you should setup your backend replacing IPv6 addresses by "::1" and inhibit IP6 usage. IPv6 is available only with IP6 infrastructure. Then addon will use IPv4 address to connect to an encoder for LiveTV.

**Comment by Lexridge** [comment]
@janbar , I appreciate your rapid reply. I did as you said, and it does work. Thank you. 

I did have to delete my .kodi directory however to make it work. Deleting just the PVR database was not enough. Not sure why. Also, restoring my backup made a mess of things too. Not a biggy. I am reinstalling all my plugins manually as I type this.  I will try all this on the RPi2 later this evening. I also will upgrade my backend from F17 to F21 sometime this week, therefore updating MythTV to probably the latest version.

Again, thank you.

**Pull request merged**
