### PR TITLE
[pvr.hts] Aligned htsp message validation with HTSP specification

### PR DESCRIPTION
**Pull request by ksooo**
Aligned htsp message validation with HTSP spec (esp. corrected handling of optinal vs. mandatory fields).

Spec: https://tvheadend.org/projects/tvheadend/wiki/Htsp

### CODE REVIEW

**Comment by Jalle19** [comment]
Thanks! Does this fix anything or is it just cleanup/cosmetics?

**Comment by ksooo** [comment]
I'm not aware of a specific problem/fix, thus just cosmetics/cleanup. OTOH I did not notice any regressions... using this patch myself for some time now.

**Comment by Jalle19** [comment]
Great, thanks. There has been some changes to the PVR addons, the addon will be moved to its own repository but I haven't had time to do the necessary work yet. We'll have to leave this one here for now until the new repository is up and running.

**Comment by ksooo** [comment]
Sure. No problem. 

Is there a decision already where the (pvr) addons will be hosted in the future? I know you had/have a lengthy discussion on this.

**Comment by Jalle19** [comment]
It seems the decision has been to move the addons under the `kodi-pvr` organization. The repository for `pvr.hts` is now located at https://github.com/kodi-pvr/pvr.hts. I haven't yet had time to look into how all this works etc. (there's a guide on the forums, http://forum.kodi.tv/showthread.php?tid=219257). Ideally this PR needs to be remade to the repository mentioned above.

**Comment by opdenkamp** [comment]
That repos is meant for building the ones used by Kodi for releases. We could do development in there directly, in a separate branch, or create a fork somewhere (e.g. under tvheadend's account) in which we can both develop and then send PRs over to `kodi-pvr`. I have no preference.

**Comment by opdenkamp** [comment]
and @adamsutton ofc ;-)

**Comment by opdenkamp** [comment]
okay after talking to @FernetMenta, we need a fork of https://github.com/kodi-pvr/pvr.hts for development, because we can't protect a branch from changes in the repos from some users, which we need for releases.

we can use mine https://github.com/opdenkamp/pvr.hts on which devs can get r+w access, and which will be used for Kodi's nightly builds. or if perhaps @adamsutton can create a fork in Tvheadend's repos on which we get write access? would be easier for users to find ;-)

closing this PR for now

**Comment by ksooo** [comment]
@opdenkamp Okay, will refire the PR against https://github.com/opdenkamp/pvr.hts or will you give me write access?

**Comment by opdenkamp** [comment]
you'll get write access too as soon as you accept whatever pike sent your way ;-)
but do a PR to that repos please, even with write access. thanks!

**Pull request closed without merging**
