### PR TITLE
[pvr.mythtv] fix addon.map since 1.9.4

### PR DESCRIPTION
**Pull request by janbar**
Linking with version script on Linux.

- Includes new global functions since 1.9.4

### CODE REVIEW

**Comment by janbar** [comment]
Required to fix crash on startup with 1.9.4.

**Comment by FernetMenta** [comment]
please bump version of addon. jenkins is kicked off so this won't be included in current cycle. why are you doing those kind of fancy things which lead to this kind of issues?
anyway, all addons will be sent to their own repositories soon and this does not matter anymore.

**Comment by janbar** [comment]
Root cause was C mangling conflict with library jansson and pulse linked statically with Kodi. On Linux main primitives overrides primitives (global or local) from dynamic loaded objects as the addon. No chance. But since this release i removed jansson dependency but kept that. I will remove it later.
So i will rebase with bump.

**Comment by FernetMenta** [comment]
thanks!

**Pull request merged**
