### PR TITLE
Fix gui lib min version to match backword compatibility to skins

### PR DESCRIPTION
**Pull request by AlwinEsch**
On gui skin I has badly corrected the backword compatibility to 5.8.0, which destroy all current skins. Due to version affiliation I created this request to match skins.

### CODE REVIEW

**Comment by FernetMenta** [comment]
according to discussion on kodi 5.8.0 is correct for min API here

**Comment by MartijnKaijser** [comment]
correct. let's compile it first without this change and see if all keeps working. If not we definitely need to revise on what depends on what. Maybe they do need to be exactly the same.
@opdenkamp you have more knowledge of these requirements?

**Comment by FernetMenta** [comment]
actually it was me who introduced this :) https://github.com/xbmc/xbmc/commit/b9a99cf17c52c43dec7013a90630b93921771f8f

**Comment by AlwinEsch** [comment]
Thanks @FernetMenta, with the lib as depend to the skin version I has created a really bad situation for the skins. To have them complete independent is the best. I close this then.

**Comment by MartijnKaijser** [comment]
Ah it was you ;)
Problem is we have a "skin API" for the skin layout and a binary "addon GUI API" which not entirely dependent on each other. Perhaps the best course of action is to split these up. Because we may want to break skin compatibility by increasing the ABI but at same time don't want to do that for binary addon GUI (which is more which controls are available then the actual skin layout).

**Comment by opdenkamp** [comment]
those 2 must be split up, that's the reason for this problem.

the defined one in the header is to ensure that the add-on uses the correct ABI. adding new stuff there requires the XBMC_GUI_API_VERSION to be bumped, any change in existing methods, structs, whatever requires XBMC_GUI_MIN_API_VERSION to be bumped.

the reason for adding those and not (only) rely on the value set in the xml is that an invalid addon.xml can crash kodi completely, while a mismatch for a python add-on doesn't.

there's no relation with the one used by skins.

**Comment by FernetMenta** [comment]
how about "kodi.guilib" as id?

**Comment by MartijnKaijser** [comment]
sound good.

**Comment by opdenkamp** [comment]
sure

**Pull request closed without merging**
