### PR TITLE
Make all add-ons optional

### PR DESCRIPTION
**Pull request by frace**
Disclaimer:
This was the first time I had my hands on a Makefile and a configure script. So be aware that this approach might be wrong entirely!

I figured it might be useful to treat all add-ons to be optional.
All add-ons but `filmon` and `iptv` default to `yes`. So there has not much changed at all although `filmon` and `iptv` have their own flags now instead of sharing `--enable-addons-with-dependencies`.

Currently I'm writing an ebuild for Gentoo Linux, so it'd be quite useful to have this feature in master and future releases.

A review and constructive comments are welcome of course!

### CODE REVIEW

**Comment by opdenkamp** [comment]
shame that you didn't see https://github.com/xbmc/xbmc/pull/6227 though
makefiles are going on holiday ;)

**Comment by frace** [comment]
Oh, too bad. ^^
However I'm not quite sure whether or not I understood how pvr add-ons will be available in the future. Will these still reside as a separate package and move from Makefiles to CMake configs? Will it be possible to tell the build which add-ons we want to build optionally?

**Comment by opdenkamp** [comment]
depends on how it's built really.

**Comment by frace** [comment]
Ok, but xbmc-pvr-addons will still be an "independent" package/code base and will not be merged with the Kodi code base?

**Comment by opdenkamp** [comment]
pvr add-ons will remain separated. even more separated than before ;-)

**Comment by frace** [comment]
Great! :) Thanks a lot.

**Pull request closed without merging**
